# Generated by Django 4.1.5 on 2024-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="protocol",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
