# Generated by Django 5.0.6 on 2024-08-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_request_protocol_alter_request_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='referrer_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
